version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-build phase: verifying environment
      - java -version
      - mvn -version
      - echo Downloading dependencies...
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Build phase started...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes